# Generated by Django 3.1.1 on 2020-09-22 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_company',
            fields=[
                ('company_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email1', models.EmailField(max_length=200)),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300, null=True)),
                ('email1', models.EmailField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_due', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_cart_added1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('variety_name', models.CharField(max_length=200)),
                ('quant_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_cart_checkedout1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('variety_name', models.CharField(max_length=200)),
                ('quant_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email1', models.EmailField(max_length=200)),
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.admin_company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('product_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quant', models.IntegerField(null=True)),
                ('num_varities', models.IntegerField(null=True)),
                ('quant_type', models.CharField(choices=[('kg', 'kg'), ('quintal', 'quintal'), ('tonnes', 'tonnes'), ('not specified', 'not specified')], max_length=100)),
                ('chck', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_checkout',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('product_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quant', models.IntegerField(null=True)),
                ('num_varities', models.IntegerField(null=True)),
                ('quant_type', models.CharField(choices=[('kg', 'kg'), ('quintal', 'quintal'), ('tonnes', 'tonnes'), ('not specified', 'not specified')], max_length=100)),
                ('chck', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_variety_checkout',
            fields=[
                ('variety_name', models.CharField(max_length=200, null=True)),
                ('variety_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Product_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product_checkout')),
                ('employee_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product_variety_added',
            fields=[
                ('product', models.CharField(max_length=200, null=True)),
                ('variety_name', models.CharField(max_length=200, null=True)),
                ('variety_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product_variety',
            fields=[
                ('variety_name', models.CharField(max_length=200, null=True)),
                ('variety_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_intial_quant', models.IntegerField(null=True)),
                ('product_net_quant', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('variety_name', models.CharField(max_length=200, null=True)),
                ('quant_type', models.CharField(choices=[('kg', 'kg'), ('quintal', 'quintal'), ('tonnes', 'tonnes'), ('not specified', 'not specified')], max_length=100)),
                ('added_or_checkedout', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee'),
        ),
    ]
